### ISSUE TITLE
Multiple Data Source Dropdown Values

### ISSUE THREAD

**Issue by aqmnguyen** [movableink/movable-cli#44]
When there are multiple data source fields, regardless of the sample value in the `manifest.yml` it seems to pulls in all the referenced sample files.

For example when opening the second DS I have open in this test app I see the following: 

![screenshot 2018-07-19 17 55 40](https://user-images.githubusercontent.com/17278432/42958262-0a056dcc-8b7d-11e8-9980-d18b476acc79.png)
https://www.dropbox.com/s/vpbkrmd2xpn0ajy/Screenshot%202018-07-19%2017.55.40.png?dl=0

In the `manifest.yml` file I've only defined the `nyc.json` file.

<img width="535" alt="screenshot 2018-07-19 17 59 17" src="https://user-images.githubusercontent.com/17278432/42958455-7b60e3e8-8b7d-11e8-8d5c-e971f7475743.png">
https://www.dropbox.com/s/6ogadnv2dzh2ssu/Screenshot%202018-07-19%2017.59.17.png?dl=0

Full data source definition below: 

```yml
data_source_definitions:
  pokeapi:
    url: 'https://pokeapi.co/api/v2/pokemon/[pokemonID]/'
    type: ApiDataSource
    content_type: application/json
    name: Pokemon API
    sample_responses:
      - name: Bulbasaur
        path: sample_data/1.json
      - name: Charizard
        path: sample_data/6.json
      - name: Blastoise
        path: sample_data/9.json

  weather:
    url: 'https://api.darksky.net/forecast/[key]/[lat],[lon]'
    type: ApiDataSource
    content_type: application/json
    name: Weather API
    sample_responses:
      - name: NYC
        path: sample_data/nyc.json
```
