### ISSUE TITLE
Using SCSS for styling

### ISSUE THREAD

**Issue by jeffreydu** [movableink/movable-cli#55]
Having SCSS functionality would be great for dynamic styling.

For example, I've put in a text field to allow the user to determine how many lines to limit the text to by appending a class name
![image](https://user-images.githubusercontent.com/18515434/45156030-d20c3a80-b1d4-11e8-9564-f7c6db6c71ce.png)

To accommodate this, I have something like this in the CSS which doesn't look great

```css
.clamp-line-3 {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  height: auto !important;
  overflow: hidden;
}
.clamp-line-4 {
  display: -webkit-box;
  -webkit-line-clamp: 4;
  -webkit-box-orient: vertical;
  height: auto !important;
  overflow: hidden;
}
.clamp-line-5 {
  display: -webkit-box;
  -webkit-line-clamp: 5;
  -webkit-box-orient: vertical;
  height: auto !important;
  overflow: hidden;
}
```

If we could add functions with SCSS then we can make it look a lot cleaner.
